// Default Public CMS values — exact same shape used by the legacy
// HeroSettingForm + PublicCmsContext, kept here as a single source of truth.
// Backend schema and existing content remain unchanged.

const defaultPublicCms = {
  theme: {
    fontFamily: "inherit",
    primaryColor: "#2563EB",
    secondaryColor: "#0F172A",
    accentColor: "#CA8A04",
    textColor: "#0F172A",
    mutedTextColor: "#64748B",
    buttonRadius: "12px",
  },
  home: {
    fontFamily: "inherit",
    pageBackgroundColor: "#FFFFFF",
    titleColor: "#0F172A",
    descriptionColor: "#475569",
    titleFontSize: "48px",
    descriptionFontSize: "18px",
    buttonColor: "#2563EB",
    buttonTextColor: "#FFFFFF",
    iconColor: "#2563EB",
    hero: {
      badgeText: "🏆 Trung tâm Cờ Vua hàng đầu",
      promoLine:
        "Ưu đãi đăng ký sớm — tặng buổi học thử & tư vấn lộ trình miễn phí.",
      title: "Phát triển tư duy chiến lược cho thế hệ tương lai",
      highlightedText: "",
      description:
        "Z Chess mang đến chương trình đào tạo cờ vua chất lượng cao, giúp trẻ em phát triển tư duy logic, khả năng tập trung và kỹ năng giải quyết vấn đề.",
      primaryButtonText: "Khám phá khóa học",
      primaryButtonLink: "/courses",
      secondaryButtonText: "Xem video giới thiệu",
      secondaryButtonLink: "",
      mediaUrl: "",
      sectionBgColor: "#0F172A",
      titleColor: "#FFFFFF",
      descriptionColor: "#CBD5E1",
      titleFontSize: "56px",
    },
    courses: {
      badge: "Khóa học",
      title: "Khóa học phổ biến",
      description: "",
      buttonText: "Xem tất cả khóa học →",
      sectionBgColor: "#FFFFFF",
      badgeBgColor: "#DBEAFE",
      badgeTextColor: "#2563EB",
      titleColor: "#0F172A",
      descriptionColor: "#64748B",
      buttonBgColor: "#0F172A",
      buttonTextColor: "#FFFFFF",
      buttonBorderColor: "#E2E8F0",
      cardButtonText: "Xem chi tiết",
      cardButtonBgColor: "#0F172A",
      cardButtonTextColor: "#FFFFFF",
      cardButtonBorderColor: "#E2E8F0",
    },
    teachers: {
      badge: "Đội ngũ",
      title: "Giáo viên xuất sắc",
      description: "",
      sectionBgColor: "#F8FAFC",
      badgeBgColor: "#DBEAFE",
      badgeTextColor: "#2563EB",
      titleColor: "#0F172A",
      descriptionColor: "#64748B",
      actionButtonBgColor: "#F1F5F9",
      actionButtonTextColor: "#0F172A",
    },
    news: {
      title: "Tin Tức & Hoạt Động",
      description: "",
      buttonText: "Xem tất cả",
      mobileButtonText: "Xem tất cả tin tức",
      sectionBgColor: "#FFFFFF",
      titleColor: "#111827",
      descriptionColor: "#4B5563",
      buttonBgColor: "#F3F4F6",
      buttonTextColor: "#2563EB",
      cardButtonText: "Đọc thêm",
      cardButtonTextColor: "#2563EB",
    },
    testimonials: {
      badge: "Phản hồi",
      title: "Phụ huynh nói gì về chúng tôi",
      description: "",
      sectionBgColor: "#FFFFFF",
      badgeBgColor: "#DBEAFE",
      badgeTextColor: "#2563EB",
      titleColor: "#0F172A",
      descriptionColor: "#64748B",
    },
    contact: {
      badge: "Liên hệ",
      title: "Đăng ký học thử",
      highlightedText: "miễn phí",
      description: "",
      sectionBgColor: "#FFFFFF",
      badgeBgColor: "#DBEAFE",
      badgeTextColor: "#2563EB",
      titleColor: "#0F172A",
      highlightColor: "#CA8A04",
      descriptionColor: "#64748B",
      submitButtonText: "Đăng ký học thử miễn phí",
      submitButtonBgColor: "#2563EB",
      submitButtonTextColor: "#FFFFFF",
    },
    cta: {
      title: "Bắt đầu hành trình cờ vua",
      highlightedText: "ngay hôm nay",
      description: "",
      primaryButtonText: "Đăng ký học thử miễn phí",
      secondaryButtonText: "Tìm hiểu thêm",
      trustItem1: "Học thử miễn phí",
      trustItem2: "Không ràng buộc",
      trustItem3: "Hoàn tiền 100%",
      sectionBgColor: "#FFFFFF",
      cardBgColor: "#0F172A",
      titleColor: "#FFFFFF",
      highlightColor: "#CA8A04",
      descriptionColor: "#CBD5E1",
      primaryButtonBgColor: "#2563EB",
      primaryButtonTextColor: "#FFFFFF",
      secondaryButtonTextColor: "#FFFFFF",
      secondaryButtonBorderColor: "#334155",
      trustTextColor: "#CBD5E1",
    },
  },
  courseStore: {
    title: "KHO KHÓA HỌC VIDEO",
    description:
      "Hệ thống bài giảng chất lượng cao, giúp bạn làm chủ bàn cờ từ Khai cuộc đến Tàn cuộc.",
    pageBackgroundColor: "#F9FAFB",
    titleColor: "#FFFFFF",
    descriptionColor: "#E2E8F0",
    titleFontSize: "48px",
    descriptionFontSize: "20px",
    fontFamily: "inherit",
    buttonColor: "#2563EB",
    buttonTextColor: "#FFFFFF",
    iconColor: "#2563EB",
    heroBackground: "",
  },
  courseDetail: {},
  teachersPage: {
    title: "Đội Ngũ Giảng Viên",
    description:
      "Gặp gỡ những Kiện tướng, Huấn luyện viên tâm huyết và giàu kinh nghiệm của chúng tôi.",
    pageBackgroundColor: "#FFFFFF",
    titleColor: "#111827",
    descriptionColor: "#4B5563",
    titleFontSize: "48px",
    descriptionFontSize: "20px",
    fontFamily: "inherit",
    buttonColor: "#2563EB",
    buttonTextColor: "#FFFFFF",
    iconColor: "#2563EB",
    heroBackground: "",
  },
  newsPage: {
    title: "Tin Tức & Sự Kiện",
    description:
      "Cập nhật những thông tin mới nhất về các giải đấu, hoạt động của câu lạc bộ và kiến thức cờ vua bổ ích.",
    pageBackgroundColor: "#FFFFFF",
    titleColor: "#111827",
    descriptionColor: "#4B5563",
    titleFontSize: "48px",
    descriptionFontSize: "20px",
    fontFamily: "inherit",
    buttonColor: "#2563EB",
    buttonTextColor: "#FFFFFF",
    iconColor: "#2563EB",
    heroBackground: "",
  },
  contactPage: {
    title: "Liên Hệ Với Chúng Tôi",
    description:
      "Chúng tôi luôn sẵn sàng lắng nghe và giải đáp mọi thắc mắc của bạn về các khóa học cờ vua.",
    pageBackgroundColor: "#FFFFFF",
    titleColor: "#FFFFFF",
    descriptionColor: "#D1D5DB",
    titleFontSize: "48px",
    descriptionFontSize: "20px",
    fontFamily: "inherit",
    buttonColor: "#2563EB",
    buttonTextColor: "#FFFFFF",
    iconColor: "#2563EB",
    heroBackground: "",
  },
};

export default defaultPublicCms;
